name: rhel-9-base

on:
    push:
      paths:
        - '*/tjx-packer/scripts/rhel*'
        - '*/tjx-packer/builds/rhel-9-base.pkr.hcl'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" # or latest

      - name: Run `packer init`
        id: init
        run: "packer init ./tjx-packer/builds"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./tjx-packer/builds"